[package]
name = "map2mqtt"
version = "0.1.0"
publish = false
authors = ["Meno Abels <meno.abels@adviser.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.2.0-alpha.6"
bytes = "0.4.12"
